global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'laptops'
    static_configs:
      - targets: ['100.103.215.113:9100']
        labels:
          instance: 'Empire'
      - targets: ['100.96.230.47:9100']
        labels:
          instance: 'Ghost'
