global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'laptops'
    static_configs:
      - targets: ['100.103.215.113:8001']
        labels:
          instance: 'Empire'
      - targets: ['100.96.230.47:8001']
        labels:
          instance: 'Ghost'
